export class StyleConst {
  // 宽高
  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';

  static readonly PERCENT_10 = '10%'
  static readonly PERCENT_15 = '15%'
  static readonly PERCENT_17 = '17%'
  static readonly PERCENT_20 = '20%'
  static readonly PERCENT_25 = '25%'
  static readonly PERCENT_30 = '30%'
  static readonly PERCENT_35 = '35%'
  static readonly PERCENT_40 = '40%'
  static readonly PERCENT_45 = '45%'
  static readonly PERCENT_50 = '50%'
  static readonly PERCENT_60 = '60%'
  static readonly PERCENT_65 = '65%'
  static readonly PERCENT_70 = '70%'
  static readonly PERCENT_72 = '72%'
  static readonly PERCENT_75 = '75%'
  static readonly PERCENT_80 = '80%'
  static readonly PERCENT_85 = '85%'
  static readonly PERCENT_90 = '90%'
  static readonly PERCENT_95 = '95%'
  static readonly PERCENT_100 = '100%'
}