# 使用官方的 Node.js 镜像作为构建阶段的基础镜像
FROM node:22.2.0-alpine AS builder

# 设置工作目录
WORKDIR /app

# 安装 pnpm
RUN npm install -g pnpm

# 复制 package.json 和 package-lock.json（如果有的话）
COPY package.json pnpm-lock.yaml ./

# 安装依赖
RUN pnpm install

# 复制所有源代码到工作目录
COPY . .

# 构建应用
RUN pnpm run build

# 使用 Nginx 作为生产阶段的基础镜像
FROM nginx:alpine

# 复制构建好的文件到 Nginx 的默认静态文件目录
COPY --from=builder /app/dist /usr/share/nginx/html

# 暴露端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]