// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalAuditLogDao is internal type for wrapping internal DAO implements.
type internalAuditLogDao = *internal.AuditLogDao

// auditLogDao is the data access object for table audit_log.
// You can define custom methods on it to extend its functionality as you wish.
type auditLogDao struct {
	internalAuditLogDao
}

var (
	// AuditLog is globally public accessible object for table audit_log operations.
	AuditLog = auditLogDao{
		internal.NewAuditLogDao(),
	}
)

// Fill with you ideas below.
