// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalChargeOrderDao is internal type for wrapping internal DAO implements.
type internalChargeOrderDao = *internal.ChargeOrderDao

// chargeOrderDao is the data access object for table charge_order.
// You can define custom methods on it to extend its functionality as you wish.
type chargeOrderDao struct {
	internalChargeOrderDao
}

var (
	// ChargeOrder is globally public accessible object for table charge_order operations.
	ChargeOrder = chargeOrderDao{
		internal.NewChargeOrderDao(),
	}
)

// Fill with you ideas below.
