// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalChargePriceDao is internal type for wrapping internal DAO implements.
type internalChargePriceDao = *internal.ChargePriceDao

// chargePriceDao is the data access object for table charge_price.
// You can define custom methods on it to extend its functionality as you wish.
type chargePriceDao struct {
	internalChargePriceDao
}

var (
	// ChargePrice is globally public accessible object for table charge_price operations.
	ChargePrice = chargePriceDao{
		internal.NewChargePriceDao(),
	}
)

// Fill with you ideas below.
