// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalPayRecordDao is internal type for wrapping internal DAO implements.
type internalPayRecordDao = *internal.PayRecordDao

// payRecordDao is the data access object for table pay_record.
// You can define custom methods on it to extend its functionality as you wish.
type payRecordDao struct {
	internalPayRecordDao
}

var (
	// PayRecord is globally public accessible object for table pay_record operations.
	PayRecord = payRecordDao{
		internal.NewPayRecordDao(),
	}
)

// Fill with you ideas below.
