// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalPileDao is internal type for wrapping internal DAO implements.
type internalPileDao = *internal.PileDao

// pileDao is the data access object for table pile.
// You can define custom methods on it to extend its functionality as you wish.
type pileDao struct {
	internalPileDao
}

var (
	// Pile is globally public accessible object for table pile operations.
	Pile = pileDao{
		internal.NewPileDao(),
	}
)

// Fill with you ideas below.
