// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalRolePermissionDao is internal type for wrapping internal DAO implements.
type internalRolePermissionDao = *internal.RolePermissionDao

// rolePermissionDao is the data access object for table role_permission.
// You can define custom methods on it to extend its functionality as you wish.
type rolePermissionDao struct {
	internalRolePermissionDao
}

var (
	// RolePermission is globally public accessible object for table role_permission operations.
	RolePermission = rolePermissionDao{
		internal.NewRolePermissionDao(),
	}
)

// Fill with you ideas below.
