// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalStationDao is internal type for wrapping internal DAO implements.
type internalStationDao = *internal.StationDao

// stationDao is the data access object for table station.
// You can define custom methods on it to extend its functionality as you wish.
type stationDao struct {
	internalStationDao
}

var (
	// Station is globally public accessible object for table station operations.
	Station = stationDao{
		internal.NewStationDao(),
	}
)

// Fill with you ideas below.
