// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"login-demo/internal/dao/internal"
)

// internalWxUserDao is internal type for wrapping internal DAO implements.
type internalWxUserDao = *internal.WxUserDao

// wxUserDao is the data access object for table wx_user.
// You can define custom methods on it to extend its functionality as you wish.
type wxUserDao struct {
	internalWxUserDao
}

var (
	// WxUser is globally public accessible object for table wx_user operations.
	WxUser = wxUserDao{
		internal.NewWxUserDao(),
	}
)

// Fill with you ideas below.
