
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
    - link:     "sqlite::@file(manifest/db/user.db)"
      tables:   "user,tenant,station,pile,charge_order,charge_price,pay_record,user_wallet,wx_user,role,role_permission,audit_log"
      jsonCase: "CamelLower"
      tplDaoInternalPath: "hack/dao_intervel_tpl.tmp"