// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ChargeOrderDao is the data access object for table charge_order.
type ChargeOrderDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns ChargeOrderColumns // columns contains all the column names of Table for convenient usage.
}

// ChargeOrderColumns defines and stores column names for table charge_order.
type ChargeOrderColumns struct {
	Id        string //
	TenantId  string //
	OrderCode string //
	UserId    string //
	StationId string //
	PileId    string //
	StartAt   string //
	StopAt    string //
	State     string //
	Price     string //
	CreateAt  string //
	UpdateAt  string //
}

// chargeOrderColumns holds the columns for table charge_order.
var chargeOrderColumns = ChargeOrderColumns{
	Id:        "id",
	TenantId:  "tenant_id",
	OrderCode: "order_code",
	UserId:    "user_id",
	StationId: "station_id",
	PileId:    "pile_id",
	StartAt:   "start_at",
	StopAt:    "stop_at",
	State:     "state",
	Price:     "price",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
}

// NewChargeOrderDao creates and returns a new DAO object for table data access.
func NewChargeOrderDao() *ChargeOrderDao {
	return &ChargeOrderDao{
		group:   "default",
		table:   "charge_order",
		columns: chargeOrderColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ChargeOrderDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ChargeOrderDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ChargeOrderDao) Columns() ChargeOrderColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ChargeOrderDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ChargeOrderDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx).Hook(TenantHook)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ChargeOrderDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
