// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PayRecordDao is the data access object for table pay_record.
type PayRecordDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns PayRecordColumns // columns contains all the column names of Table for convenient usage.
}

// PayRecordColumns defines and stores column names for table pay_record.
type PayRecordColumns struct {
	Id       string //
	PayCode  string //
	UserId   string //
	State    string //
	Price    string //
	PayAt    string //
	CreateAt string //
	UpdateAt string //
}

// payRecordColumns holds the columns for table pay_record.
var payRecordColumns = PayRecordColumns{
	Id:       "id",
	PayCode:  "pay_code",
	UserId:   "user_id",
	State:    "state",
	Price:    "price",
	PayAt:    "pay_at",
	CreateAt: "create_at",
	UpdateAt: "update_at",
}

// NewPayRecordDao creates and returns a new DAO object for table data access.
func NewPayRecordDao() *PayRecordDao {
	return &PayRecordDao{
		group:   "default",
		table:   "pay_record",
		columns: payRecordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PayRecordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PayRecordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PayRecordDao) Columns() PayRecordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PayRecordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PayRecordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PayRecordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
