// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PileDao is the data access object for table pile.
type PileDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns PileColumns // columns contains all the column names of Table for convenient usage.
}

// PileColumns defines and stores column names for table pile.
type PileColumns struct {
	Id        string //
	Code      string //
	StationId string //
	State     string //
	CreateAt  string //
	UpdateAt  string //
}

// pileColumns holds the columns for table pile.
var pileColumns = PileColumns{
	Id:        "id",
	Code:      "code",
	StationId: "station_id",
	State:     "state",
	CreateAt:  "create_at",
	UpdateAt:  "update_at",
}

// NewPileDao creates and returns a new DAO object for table data access.
func NewPileDao() *PileDao {
	return &PileDao{
		group:   "default",
		table:   "pile",
		columns: pileColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PileDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PileDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PileDao) Columns() PileColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PileDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PileDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PileDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
