// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserWalletDao is the data access object for table user_wallet.
type UserWalletDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns UserWalletColumns // columns contains all the column names of Table for convenient usage.
}

// UserWalletColumns defines and stores column names for table user_wallet.
type UserWalletColumns struct {
	UserId   string //
	Balance  string //
	CreateAt string //
	UpdateAt string //
}

// userWalletColumns holds the columns for table user_wallet.
var userWalletColumns = UserWalletColumns{
	UserId:   "user_id",
	Balance:  "balance",
	CreateAt: "create_at",
	UpdateAt: "update_at",
}

// NewUserWalletDao creates and returns a new DAO object for table data access.
func NewUserWalletDao() *UserWalletDao {
	return &UserWalletDao{
		group:   "default",
		table:   "user_wallet",
		columns: userWalletColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserWalletDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserWalletDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserWalletDao) Columns() UserWalletColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserWalletDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserWalletDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserWalletDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
